import { useMutation } from '@tanstack/react-query';
import { Link, Navigate, useRouterState } from '@tanstack/react-router';
import { useState } from 'react';

import { loginCheckpoint } from '@/api/auth';
import { AuthLayout } from '@/components/auth/AuthLayout';
import { FormError } from '@/components/auth/FormError';
import { Button } from '@/components/ui/button';
import { Field, FieldDescription, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { InputOTP, InputOTPGroup, InputOTPSlot } from '@/components/ui/input-otp';
import { Spinner } from '@/components/ui/spinner';
import { httpErrorToHuman } from '@/lib/http';

const CODE_LENGTH = 6;

const LoginCheckpointPage: React.FC = () => {
    const confirmationToken = useRouterState({ select: (state) => state.location.state.confirmationToken });
    const [isMissingDevice, setIsMissingDevice] = useState(false);
    const [code, setCode] = useState('');
    const [recoveryToken, setRecoveryToken] = useState('');

    const mutation = useMutation({
        mutationFn: loginCheckpoint,
        onSuccess: (response) => {
            if (response.complete) {
                window.location.href = response.intended ?? '/';
            }
        },
    });

    if (!confirmationToken) {
        return <Navigate to='/auth/login' replace />;
    }

    const isBusy = mutation.isPending || (mutation.isSuccess && mutation.data.complete);
    const isComplete = isMissingDevice ? recoveryToken.length > 0 : code.length === CODE_LENGTH;

    const submit = (values: { code: string; recoveryToken: string }) => {
        mutation.mutate({ confirmationToken, ...values });
    };

    const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        if (!isComplete) {
            return;
        }

        submit({ code, recoveryToken });
    };

    const handleToggleDevice = () => {
        setCode('');
        setRecoveryToken('');
        mutation.reset();
        setIsMissingDevice((value) => !value);
    };

    return (
        <AuthLayout title='Device checkpoint' description='This account is protected with two-factor authentication.'>
            <form onSubmit={handleSubmit} noValidate>
                <FieldGroup>
                    <FormError message={mutation.error ? httpErrorToHuman(mutation.error) : null} />
                    {isMissingDevice ? (
                        <Field>
                            <FieldLabel htmlFor='recovery-token'>Recovery Code</FieldLabel>
                            <Input
                                id='recovery-token'
                                autoFocus
                                autoComplete='off'
                                disabled={isBusy}
                                value={recoveryToken}
                                onChange={(event) => setRecoveryToken(event.target.value)}
                            />
                            <FieldDescription>
                                Enter one of the recovery codes generated when you set up two-factor authentication.
                            </FieldDescription>
                        </Field>
                    ) : (
                        <Field>
                            <FieldLabel htmlFor='code'>Authentication Code</FieldLabel>
                            <InputOTP
                                id='code'
                                maxLength={CODE_LENGTH}
                                autoFocus
                                disabled={isBusy}
                                value={code}
                                onChange={setCode}
                                onComplete={(value: string) => submit({ code: value, recoveryToken: '' })}
                            >
                                <InputOTPGroup>
                                    {Array.from({ length: CODE_LENGTH }, (_, index) => (
                                        <InputOTPSlot key={index} index={index} />
                                    ))}
                                </InputOTPGroup>
                            </InputOTP>
                            <FieldDescription>Enter the code generated by your authenticator app.</FieldDescription>
                        </Field>
                    )}
                    <Button type='submit' disabled={isBusy || !isComplete}>
                        {isBusy && <Spinner />}
                        Continue
                    </Button>
                    <div className='flex items-center justify-between text-sm text-muted-foreground'>
                        <Button type='button' variant='link' className='h-auto p-0' onClick={handleToggleDevice}>
                            {isMissingDevice ? 'I have my device' : "I've lost my device"}
                        </Button>
                        <Link to='/auth/login' className='underline-offset-4 hover:underline'>
                            Return to login
                        </Link>
                    </div>
                </FieldGroup>
            </form>
        </AuthLayout>
    );
};

export { LoginCheckpointPage };
